Repository MatthewComtois/oxygen-cs-grp2-eq1, pull requests merged in 2023-07, with the labels that each got.

#10 Documentation et amélioration
  .github/workflows/main.yml
  .pre-commit-config.yaml
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  doc/ChoixLabel.md
  doc/ChoixMilestone.md
  doc/ChoixTagDockerHub.md
  doc/ChoixTechnologiques.md
  doc/ModelBugFix.md
  doc/ModelDoc.md
  doc/ModelNewFeature.md
  doc/ModelPullRequest.md
  doc/PolitiqueBranches.md
  doc/ProjetEtKanban.md
  pytest.ini
  src/database.py
  src/main.py
  src/utils.py
  test/test_database.py
  test/test_utils.py
Labels: documentation, enhancement

#11 Ajout doc Github Action, pre-commit, docker
  doc/ChoixIntegrationContinue.md
  doc/ChoixTechnologiques.md
Labels: documentation

#12 Remise Lab 2
  .dockerignore
  .github/workflows/main.yml
  .pre-commit-config.yaml
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  doc/ChoixIntegrationContinue.md
  doc/ChoixLabel.md
  doc/ChoixMilestone.md
  doc/ChoixTagDockerHub.md
  doc/ChoixTechnologiques.md
  doc/ModelBugFix.md
  doc/ModelDoc.md
  doc/ModelNewFeature.md
  doc/ModelPullRequest.md
  doc/PolitiqueBranches.md
  doc/ProjetEtKanban.md
  docker-compose.yml
  lint.py
  pytest.ini
  src/database.py
  src/main.py
  src/utils.py
  test/test_database.py
  test/test_utils.py
Labels: documentation, enhancement, Fondation

#15 Validate CD works
  .github/workflows/main.yml
  mysql-pod.yaml
  mysql-service.yaml
  oxygencs-deployment.yaml
  src/database.py
  src/main.py
Labels: enhancement

#18 PR ajout documentation
  mysql-pod.yaml
Labels: documentation
